### PR TITLE
Compatibility for core version 0.8.6

### LINKED ISSUE #31: The add-on does not work in 0.8.x versions or 0.7.10
The add-on no longer works in 0.8.x version.
image

In 0.7.10 it was not working properly as once the brush was selected and the user switched to another tool, the brush continued to function and return to SimpleFox toolset was impossible unless reload was issued via F5

### PR DESCRIPTION
**Pull request by Azzurite**
Fixes #31

Needs a tag `0.1.18` so the download link works, otherwise this should be good to go.

### CODE REVIEW

**Comment by Azzurite** [comment]
Actually hold that thought - might've discovered an issue

**Comment by Azzurite** [comment]
Should be good now. I tested all the main features.

**Comment by crhampton1** [comment]
Sweet, thanks! I'll get this merged and released this afternoon. Thanks!

**Review by crhampton1 — COMMENTED** [review]
Great!

**Pull request merged**
